export default {
    path:'/movie',
    component:()=>import('@/views/Movie'),
    children:[
        {
            path:'',
            redirect:'nowPlaying'
        },
        {
            path:'city',
            component:()=>import('@/components/City')
        },
        {
            path:'commingPlaying',
            component:()=>import('@/components/CommingPlaying')
        },
        {
            path:'search',
            component:()=>import('@/components/Search')
        },
        {
            path:'nowPlaying',
            component:()=>import('@/components/NowPlaying')
        }
    ]
}